# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-github-metadata

exclude:
  - "/vendor/"

# Site settings
title: Random Thoughts about Software Development and Cyber Security
subtitle: "by Olivier Vaillancourt"
email: ''
name: Olivier Vaillancourt
description: >
  This blog expresses my own opinions on topics that I like. (Copyright Olivier Vaillancourt 2021)
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: '' # the subpath of your site, e.g. /blog/
repository: oliviervaillancourt/blog
url: "https://oliviervaillancourt.com" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"
permalink: /posts/:title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Disqus comments
# disqus_shortname: bencentra

# Google analytics
ga_tracking_id: "UA-111578565-1"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: "@olivaillancourt"
    url: https://twitter.com/olivaillancourt
    desc: Follow me on Twitter
    share: true

#  - name: Facebook
#    icon: facebook
#    username: thebencentra
#    url:
#    desc: Friend me on Facebook
#    share: true

  - name: GitHub
    icon: github
    username: oliviervaillancourt
    url: https://github.com/oliviervaillancourt
    desc: Fork me on GitHub
    share: false
 
# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/oliviervaillancourt/blog"
    os_rcs_type: "git"
    os_src: "git@github.com:oliviervaillancourt/blog.git"
